/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-05-25 17:48:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" />\n");
      out.write("        <title>F8 DEMO</title>\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta name=\"description\" content=\"Premium Bootstrap 4 Landing Page Template\" />\n");
      out.write("        <meta name=\"keywords\" content=\"Appointment, Booking, System, Dashboard, Health\" />\n");
      out.write("        <meta name=\"author\" content=\"Shreethemes\" />\n");
      out.write("        <meta name=\"email\" content=\"support@shreethemes.in\" />\n");
      out.write("        <meta name=\"website\" content=\"https://shreethemes.in\" />\n");
      out.write("        <meta name=\"Version\" content=\"v1.2.0\" />\n");
      out.write("        <!-- favicon -->\n");
      out.write("        <link rel=\"shortcut icon\" href=\"assets/images/favicon.ico.png\">\n");
      out.write("        <!-- Bootstrap -->\n");
      out.write("        <link href=\"assets/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- Icons -->\n");
      out.write("        <link href=\"assets/css/materialdesignicons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"assets/css/remixicon.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"https://unicons.iconscout.com/release/v3.0.6/css/line.css\"  rel=\"stylesheet\">\n");
      out.write("        <!-- Css -->\n");
      out.write("        <link href=\"assets/css/style.min.css\" rel=\"stylesheet\" type=\"text/css\" id=\"theme-opt\" />\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <!-- Loader -->\n");
      out.write("        <div id=\"preloader\">\n");
      out.write("            <div id=\"status\">\n");
      out.write("                <div class=\"spinner\">\n");
      out.write("                    <div class=\"double-bounce1\"></div>\n");
      out.write("                    <div class=\"double-bounce2\"></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Loader -->\n");
      out.write("\n");
      out.write("        <div class=\"back-to-home rounded d-none d-sm-block\">\n");
      out.write("            <a href=\"home\" class=\"btn btn-icon btn-primary\"><i data-feather=\"home\" class=\"icons\"></i></a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Hero Start -->\n");
      out.write("        <section class=\"bg-home d-flex bg-light align-items-center\" style=\"background: url('assets/images/bg/bg-lines-one.png') center;\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row justify-content-center\">\n");
      out.write("                    <div class=\"col-lg-5 col-md-8\">\n");
      out.write("                        <img src=\"assets/images/logo-dark.png\" height=\"24\" class=\"mx-auto d-block\" alt=\"\">\n");
      out.write("                        <div class=\"card login-page bg-white shadow mt-4 rounded border-0\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h4 class=\"text-center\">Sign In</h4>  \n");
      out.write("                                <form action=\"login\" method=\"post\" class=\"login-form mt-4\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-lg-12\">\n");
      out.write("                                            <div class=\"mb-3\">\n");
      out.write("                                                <label class=\"form-label\">Email <span class=\"text-danger\">*</span></label>\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" placeholder=\"Email\" name=\"email\" required=\"\">\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-lg-12\">\n");
      out.write("                                            <div class=\"mb-3\">\n");
      out.write("                                                <label class=\"form-label\">Password <span class=\"text-danger\">*</span></label>\n");
      out.write("                                                <input type=\"password\" class=\"form-control\" placeholder=\"Password\" name=\"password\" required=\"\">\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-lg-12\">\n");
      out.write("                                            <div class=\"d-flex justify-content-between\">\n");
      out.write("                                                <div class=\"mb-3\">\n");
      out.write("                                                    <div class=\"form-check\">\n");
      out.write("                                                        <input class=\"form-check-input align-middle\" type=\"checkbox\" value=\"\" id=\"remember-check\">\n");
      out.write("                                                        <label class=\"form-check-label\" for=\"remember-check\">Remember me</label>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <a href=\"forgot-password.html\" class=\"text-dark h6 mb-0\">Forgot password ?</a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-lg-12\">\n");
      out.write("                                            <div class=\"mb-3\">\n");
      out.write("                                                <span style=\"color:red; \">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgUserName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                                                <span style=\"color:red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgPass}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                                                <span style=\"color:red; \">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-lg-12 mb-0\">\n");
      out.write("                                            <div class=\"d-grid\">\n");
      out.write("                                                <button class=\"btn btn-primary\">Sign in</button>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-lg-12 mt-3 text-center\">\n");
      out.write("                                            <h6 class=\"text-muted\">Or</h6>\n");
      out.write("                                        </div><!--end col-->\n");
      out.write("\n");
      out.write("                                        <div class=\"col-6 mt-3\">\n");
      out.write("                                            <div class=\"d-grid\">\n");
      out.write("                                                <a href=\"https://www.facebook.com/dialog/oauth?client_id=556229513371886&redirect_uri=http://localhost:9999/F8_Group6_td/loginWithFb\" class=\"btn btn-soft-primary\">\n");
      out.write("                                                    <i class=\"uil uil-facebook\"></i> Facebook</a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div><!--end col-->\n");
      out.write("\n");
      out.write("                                        <div class=\"col-6 mt-3\">\n");
      out.write("                                            <div class=\"d-grid\">\n");
      out.write("                                                <a href=\"https://accounts.google.com/o/oauth2/auth?scope=email%20profile&&redirect_uri=http://localhost:9999/F8_Group6_td/loginwithgg&response_type=code&client_id=358017925071-1bsfop7rm7fag4isfoej2nk8luannmc0.apps.googleusercontent.com&approval_prompt=force\" \n");
      out.write("                                                   class=\"btn btn-soft-primary\"><i class=\"uil uil-google\"></i> Google</a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div><!--end col-->\n");
      out.write("\n");
      out.write("                                        <div class=\"col-12 text-center\">\n");
      out.write("                                            <p class=\"mb-0 mt-3\"><small class=\"text-dark me-2\">Don't have an account ?</small> <a href=\"register\" class=\"text-dark fw-bold\">Sign Up</a></p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div><!---->\n");
      out.write("                    </div> <!--end col-->\n");
      out.write("                </div><!--end row-->\n");
      out.write("            </div> <!--end container-->\n");
      out.write("        </section><!--end section-->\n");
      out.write("        <!-- Hero End -->\n");
      out.write("\n");
      out.write("        <!-- javascript -->\n");
      out.write("        <script src=\"assets/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <!-- Icons -->\n");
      out.write("        <script src=\"assets/js/feather.min.js\"></script>\n");
      out.write("        <!-- Main Js -->\n");
      out.write("        <script src=\"assets/js/app.js\"></script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
